### ISSUE TITLE
Table of content not working

### ISSUE THREAD

**Issue by miles5600** [xanny-projects/xanny#2]
## Current behavior

Full example, headers, configuration, installation not redirecting.

## Expected behavior

To just work.

</code></pre>

**Comment by getspooky** [comment]
@miles5600 
I will fix it 👍

**Comment by miles5600** [comment]
Ok, thanks

**Comment by getspooky** [comment]
Hi @miles5600 
I am currently working on officiel xanny-projects website, so i will move documentation from README.MD file to website.

**Comment by getspooky** [comment]
@miles5600  Fixed
